# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies without running prepare scripts
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts

# Copy source and build
COPY . .
RUN npm run build

# Runtime stage
FROM node:lts-alpine
WORKDIR /app

# Copy built artifacts and install production dependencies
COPY --from=builder /app/dist ./dist
COPY package.json package-lock.json ./
RUN npm install --production --ignore-scripts

# Default environment
ENV NODE_ENV=production

# Default execution command
ENTRYPOINT ["node", "./dist/index.js"]
